# Generated by Django 4.2.10 on 2024-02-28 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buisnessapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='CPassword',
        ),
    ]
