# Generated by Django 4.2.10 on 2024-02-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buisnessapp', '0002_remove_userregister_cpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='businessproposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BName', models.CharField(max_length=30)),
                ('CRegNo', models.IntegerField()),
                ('Category', models.CharField(max_length=30)),
                ('Objective', models.TextField()),
                ('Lifetime', models.TextField()),
                ('Experience', models.CharField(max_length=30)),
                ('SkillSet', models.CharField(max_length=100)),
                ('ContactNo', models.BigIntegerField()),
                ('Address', models.TextField()),
                ('Status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=30)),
            ],
        ),
    ]
