# Generated by Django 4.2.10 on 2024-02-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buisnessapp', '0004_businessproposal_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Query', models.TextField()),
                ('Reply', models.TextField()),
            ],
        ),
    ]
