# Generated by Django 4.2.10 on 2024-02-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buisnessapp', '0005_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='Reply',
            field=models.TextField(default='Pending your query reply'),
        ),
    ]
