# Generated by Django 4.2.10 on 2024-03-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buisnessapp', '0007_appliedjobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='interestedinvestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusinessMan', models.CharField(max_length=30)),
                ('Business', models.CharField(max_length=30)),
                ('Applicant', models.CharField(max_length=30)),
                ('InvestmentType', models.CharField(max_length=30)),
                ('Amount', models.IntegerField()),
                ('TimeofInvestment', models.CharField(max_length=30)),
                ('Status', models.CharField(choices=[('pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined your interest', 'Declined')], default='pending your interest', max_length=30)),
            ],
        ),
    ]
